version: "3.3"
services:
  app:
    container_name: app
    build:
      context: .
      args:
        - SIGN_IN_EMAIL=${SIGN_IN_EMAIL}
        - SIGN_IN_PASSWORD=${SIGN_IN_PASSWORD}
    command: ["pytest", "--tracing on"]
    volumes:
      - .:/application/src
